# Generated by Django 5.0 on 2023-12-09 12:04

from django.db import migrations

def init_data(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Timer = apps.get_model('api', 'Timer')
    User.objects.create_user('john', first_name='John', last_name='Doe')
    Timer.objects.create(user_id=1, pomodoro=25, short_break=5, long_break=30, sleep_time='23:00')

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(init_data),
    ]
