# Generated by Django 4.2.8 on 2023-12-17 08:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_post_thumbnail_video_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
