version: "3.9"
services:
    database:
        container_name: pomodoro-mysql
        image: mysql:latest
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        ports:
            - ${MYSQL_HOST_PORT}:${MYSQL_PORT}
        networks:
            - pomodoro-network

    frontend:
        build: ./frontend
        container_name: pomodoro-frontend
        ports:
            - ${REACT_HOST_PORT}:${REACT_PORT}
        networks:
            - pomodoro-network

    backend:
        build: ./backend
        container_name: pomodoro-backend
        restart: on-failure
        ports:
            - ${API_HOST_PORT}:8000
        networks:
            - pomodoro-network
        depends_on:
            - database

    phpmyadmin:
        container_name: pomodoro-phpmyadmin
        image: phpmyadmin/phpmyadmin:latest
        environment:
            PMA_HOSTS: database
            PMA_PORT: ${MYSQL_HOST_PORT}
            PMA_USER: ${MYSQL_USER}
            PMA_PASSWORD : ${MYSQL_PASSWORD}
        ports:
          - ${PMA_HOST_PORT}:${PMA_PORT}
        networks:
            - pomodoro-network
        depends_on:
            - database

networks:
    pomodoro-network:
        driver: bridge
